/************************************************************
 This file is automatically generated by the tool, please do not modify it directly。
 *************************************************************/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameFramework.Runtime;

namespace GameMain
{
    /// <summary>
    /// test
    /// </summary>
    public class DTperson : DataRowBase
    {
        private int mId = 0;

        /// <summary>
        /// 
        /// </summary>
        public override int Id => mId;

        /// <summary>
        /// 姓名
        /// </summary>
        public string Name {get; private set;}

        /// <summary>
        /// 性别
        /// </summary>
        public string Sex {get; private set;}

        /// <summary>
        /// 年龄
        /// </summary>
        public int Age {get; private set;}


        public override bool ParseDataRow(string dataRowString, object userData)
        {
            var columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
            for (var i = 0; i < columnStrings.Length; i++)
            {
                columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
            }

            var index = 0;
            index++;
            mId = int.Parse(columnStrings[index++]);
            index++;
            Name = columnStrings[index++];
            Sex = columnStrings[index++];
            Age = int.Parse(columnStrings[index++]);

            GeneratePropertyArray();
            return true;
        }

        public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using (var memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
            {
                using (var binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
                {
                    mId = binaryReader.Read7BitEncodedInt32();
                    Name = binaryReader.ReadString();
                    Sex = binaryReader.ReadString();
                    Age = binaryReader.Read7BitEncodedInt32();
                }
            }

            GeneratePropertyArray();
            return true;
        }


        private void GeneratePropertyArray()
        {
        }
    }
}