/************************************************************
 This file is automatically generated by the tool, please do not modify it directly。
 *************************************************************/

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityGameFramework.Runtime;

namespace GameMain
{
    /// <summary>
    /// LevelTable
    /// </summary>
    public class DTLevelTable : DataRowBase
    {
        private int mId = 0;

        /// <summary>
        /// 
        /// </summary>
        public override int Id => mId;

        /// <summary>
        /// 难度等级
        /// </summary>
        public string DiffcultLevel {get; private set;}

        /// <summary>
        /// 起始索引号
        /// </summary>
        public int StartIndex {get; private set;}

        /// <summary>
        /// 末尾索引号
        /// </summary>
        public int EndIndex {get; private set;}


        public override bool ParseDataRow(string dataRowString, object userData)
        {
            var columnStrings = dataRowString.Split(DataTableExtension.DataSplitSeparators);
            for (var i = 0; i < columnStrings.Length; i++)
            {
                columnStrings[i] = columnStrings[i].Trim(DataTableExtension.DataTrimSeparators);
            }

            var index = 0;
            index++;
            mId = int.Parse(columnStrings[index++]);
            index++;
            DiffcultLevel = columnStrings[index++];
            StartIndex = int.Parse(columnStrings[index++]);
            EndIndex = int.Parse(columnStrings[index++]);

            GeneratePropertyArray();
            return true;
        }

        public override bool ParseDataRow(byte[] dataRowBytes, int startIndex, int length, object userData)
        {
            using (var memoryStream = new MemoryStream(dataRowBytes, startIndex, length, false))
            {
                using (var binaryReader = new BinaryReader(memoryStream, Encoding.UTF8))
                {
                    mId = binaryReader.Read7BitEncodedInt32();
                    DiffcultLevel = binaryReader.ReadString();
                    StartIndex = binaryReader.Read7BitEncodedInt32();
                    EndIndex = binaryReader.Read7BitEncodedInt32();
                }
            }

            GeneratePropertyArray();
            return true;
        }


        private void GeneratePropertyArray()
        {
        }
    }
}